const ADD = "ADD";
const RESET = "RESET";
const FETCHDRINKSEARCH = "FETCHDRINKSEARCH";
const DRINKTODISPLAY = "DRINKTODISPLAY";

export default {
  ADD,
  RESET,
  FETCHDRINKSEARCH,
  DRINKTODISPLAY,
};
