const ADD = "ADD";
const REMOVE = "REMOVE";

const RESET = "RESET";
const FETCHDRINKSEARCH = "FETCHDRINKSEARCH";
const DRINKTODISPLAY = "DRINKTODISPLAY";

export default {
  ADD,
  REMOVE,
  RESET,
  FETCHDRINKSEARCH,
  DRINKTODISPLAY,
};
